baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yarden Wolf'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-4N2492LZRJ"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Finance Blog"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
This blog is a documentation of my side-projects and independent research in Finance.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/yarden-evan-wolf/"

[[params.social]]
name = "github"
url = "https://github.com/yardenwolf"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
